apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-go-basic-muwe
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-go-basic-muwe
    app.kubernetes.io/part-of: devfile-sample-go-basic-1
  name: devfile-sample-go-basic-muwe
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: go-app
      app.kubernetes.io/instance: devfile-sample-go-basic-muwe
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: go-app
        app.kubernetes.io/instance: devfile-sample-go-basic-muwe
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/karthik-jk-tenant/devfile-sample-go-basic-1/devfile-sample-go-basic-muwe@sha256:b905bffb1f976d0cef420be3aa722da2d77578000ddaa43196cffa4fce60e338
        name: my-go
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
status: {}
